name: deprecations-io/monolog-handler

on:
    pull_request: ~
    push:
        branches:
            - main

jobs:
    coding-style:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: none
            - name: php-cs-fixer
              run: |
                  wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.2/php-cs-fixer.phar -q
                  php php-cs-fixer.phar fix --dry-run --diff

    phpunit:
        name: phpunit (PHP ${{ matrix.php-version }} | Composer ${{ matrix.composer }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '5.3'
                    - '5.4'
                    - '5.5'
                    - '5.6'
                    - '7.0'
                    - '7.1'
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'
                composer:
                    - 'v1'
                    - 'v2'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                coverage: none
                php-version: ${{ matrix.php-version }}
                tools: composer:${{ matrix.composer }}

            #
            # Monolog 3
            #
            - name: Tests | monolog 3.* | highest
              if: matrix.php-version >= '8.1'
              run: |
                  composer require --no-update "monolog/monolog=3.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit

            - name: Tests | monolog 3.* | lowest
              if: matrix.php-version >= '8.1'
              run: |
                  composer require --no-update "monolog/monolog=3.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress --prefer-lowest
                  php vendor/bin/phpunit
