name: deprecations-io/monolog-handler

on:
    pull_request: ~
    push:
        branches:
            - main

jobs:
    coding-style:
        name: php-cs-fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none
            - name: php-cs-fixer
              run: |
                  wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.2/php-cs-fixer.phar -q
                  php php-cs-fixer.phar fix --dry-run --diff

    phpunit:
        name: phpunit (PHP ${{ matrix.php-version }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '5.3'
                    - '5.4'
                    - '5.5'
                    - '5.6'
                    - '7.0'
                    - '7.1'
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'
                    - '8.2'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            #
            # PHP and Composer install
            #
            - name: Install PHP and Composer v1 (PHP 5.3)
              if: matrix.php-version == '5.3'
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v1

            - name: Install PHP and Composer v2 (PHP 5.4+)
              if: matrix.php-version != '5.3'
              uses: shivammathur/setup-php@v2
              with:
                coverage: none
                php-version: ${{ matrix.php-version }}
                tools: composer:v2

            #
            # PHPUnit install
            #
            - name: Install phpunit 4.* (PHP 5.3 to 7.2)
              if: matrix.php-version < '7.3'
              run: composer require --dev --no-update "phpunit/phpunit=4.*"

            - name: Install phpunit 9.* (PHP 7.3+)
              if: matrix.php-version >= '7.3'
              run: composer require --dev --no-update "phpunit/phpunit=9.*"

            #
            # Monolog 1
            #
            - name: Tests | monolog 1.* | highest
              run: |
                  composer require --no-update "monolog/monolog=1.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit

            - name: Tests | monolog 1.* | lowest
              run: |
                  composer require --no-update "monolog/monolog=1.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress --prefer-lowest
                  php vendor/bin/phpunit

            #
            # Monolog 2
            #
            - name: Tests | monolog 2.* | highest
              if: matrix.php-version >= '7.2'
              run: |
                  composer require --no-update "monolog/monolog=2.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit

            - name: Tests | monolog 2.* | lowest
              if: matrix.php-version >= '7.2'
              run: |
                  composer require --no-update "monolog/monolog=2.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress --prefer-lowest
                  php vendor/bin/phpunit

            #
            # Monolog 3
            #
            - name: Tests | monolog 3.* | highest
              if: matrix.php-version >= '8.1'
              run: |
                  composer require --no-update "monolog/monolog=3.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit

            - name: Tests | monolog 3.* | lowest
              if: matrix.php-version >= '8.1'
              run: |
                  composer require --no-update "monolog/monolog=3.*"
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress --prefer-lowest
                  php vendor/bin/phpunit
